In [1]:
import duckdb as db
import polars as pl
from extract import *

In [2]:
get_sports()

shape: (20, 7)
┌──────┬──────┬─────────────────────┬────────────────────┬──────────────┬───────────┬──────────────┐
│ id   ┆ code ┆ link                ┆ name               ┆ abbreviation ┆ sortOrder ┆ activeStatus │
│ ---  ┆ ---  ┆ ---                 ┆ ---                ┆ ---          ┆ ---       ┆ ---          │
│ i64  ┆ str  ┆ str                 ┆ str                ┆ str          ┆ i64       ┆ bool         │
╞══════╪══════╪═════════════════════╪════════════════════╪══════════════╪═══════════╪══════════════╡
│ 1    ┆ mlb  ┆ /api/v1/sports/1    ┆ Major League       ┆ MLB          ┆ 11        ┆ true         │
│      ┆      ┆                     ┆ Baseball           ┆              ┆           ┆              │
│ 11   ┆ aaa  ┆ /api/v1/sports/11   ┆ Triple-A           ┆ AAA          ┆ 101       ┆ true         │
│ 12   ┆ aax  ┆ /api/v1/sports/12   ┆ Double-A           ┆ AA           ┆ 201       ┆ true         │
│ 13   ┆ afa  ┆ /api/v1/sports/13   ┆ High-A             ┆ A+           ┆ 301       ┆ true         │
│ 14   ┆ afx  ┆ /api/v1/sports/14   ┆ Single-A           ┆ A            ┆ 401       ┆ true         │
│ …    ┆ …    ┆ …                   ┆ …                  ┆ …            ┆ …         ┆ …            │
│ 6005 ┆ ame  ┆ /api/v1/sports/6005 ┆ International      ┆ AME          ┆ 3509      ┆ true         │
│      ┆      ┆                     ┆ Baseball (amateu…  ┆              ┆           ┆              │
│ 52   ┆ oly  ┆ /api/v1/sports/52   ┆ Olympic Baseball   ┆ OLY          ┆ 3511      ┆ true         │
│ 22   ┆ bbc  ┆ /api/v1/sports/22   ┆ College Baseball   ┆ College      ┆ 5101      ┆ true         │
│ 586  ┆ hsb  ┆ /api/v1/sports/586  ┆ High School        ┆ H.S.         ┆ 6201      ┆ true         │
│      ┆      ┆                     ┆ Baseball           ┆              ┆           ┆              │
│ 576  ┆ wps  ┆ /api/v1/sports/576  ┆ Women's            ┆ WPS          ┆ 7001      ┆ true         │
│      ┆      ┆                     ┆ Professional       ┆              ┆           ┆              │
│      ┆      ┆                     ┆ Softball           ┆              ┆           ┆              │
└──────┴──────┴─────────────────────┴────────────────────┴──────────────┴───────────┴──────────────┘

In [3]:
link_regex = r'/api/v\d(?:\.\d)?((?:/[a-zA-Z0-9]+)+)'
CREATE_sports = '''
    CREATE TABLE sports(
        sport_id INT PRIMARY KEY,
        sport_code VARCHAR(3) UNIQUE NOT NULL,
        sport_name VARCHAR(255) UNIQUE NOT NULL,
        sport_abbr VARCHAR(255) UNIQUE NOT NULL,
        sort_order INT NOT NULL CHECK (sort_order > 0),
        sport_link VARCHAR(255) UNIQUE NOT NULL
        ------------------------------------------------
        CONSTRAINT sport_link_format CHECK (sport_link ~ link_regex)
    )
'''
CREATE_sports = CREATE_sports.replace('link_regex', '\'' + link_regex + '\'')
print(CREATE_sports)

    CREATE TABLE sports(
        sport_id INT PRIMARY KEY,
        sport_code VARCHAR(3) UNIQUE NOT NULL,
        sport_name VARCHAR(255) UNIQUE NOT NULL,
        sport_abbr VARCHAR(255) UNIQUE NOT NULL,
        sort_order INT NOT NULL CHECK (sort_order > 0),
        sport_link VARCHAR(255) UNIQUE NOT NULL
        ------------------------------------------------
        CONSTRAINT sport_link_format CHECK (sport_link ~ '/api/v\d(?:\.\d)?((?:/[a-zA-Z0-9]+)+)')
    )

In [4]:
get_leagues()

shape: (118, 40)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬───────────┐
│ id   ┆ name       ┆ link       ┆ abbreviati ┆ … ┆ seasonDate ┆ seasonDate ┆ sport.id ┆ sport.lin │
│ ---  ┆ ---        ┆ ---        ┆ on         ┆   ┆ Info.quali ┆ Info.quali ┆ ---      ┆ k         │
│ i64  ┆ str        ┆ str        ┆ ---        ┆   ┆ fierPlateA ┆ fierOutsPi ┆ i64      ┆ ---       │
│      ┆            ┆            ┆ str        ┆   ┆ …          ┆ …          ┆          ┆ str       │
│      ┆            ┆            ┆            ┆   ┆ ---        ┆ ---        ┆          ┆           │
│      ┆            ┆            ┆            ┆   ┆ f64        ┆ f64        ┆          ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ 103  ┆ American   ┆ /api/v1/le ┆ AL         ┆ … ┆ 3.1        ┆ 3.0        ┆ 1        ┆ /api/v1/s │
│      ┆ League     ┆ ague/103   ┆            ┆   ┆            ┆            ┆          ┆ ports/1   │
│ 104  ┆ National   ┆ /api/v1/le ┆ NL         ┆ … ┆ 3.1        ┆ 3.0        ┆ 1        ┆ /api/v1/s │
│      ┆ League     ┆ ague/104   ┆            ┆   ┆            ┆            ┆          ┆ ports/1   │
│ 114  ┆ Cactus     ┆ /api/v1/le ┆ CL         ┆ … ┆ null       ┆ null       ┆ null     ┆ null      │
│      ┆ League     ┆ ague/114   ┆            ┆   ┆            ┆            ┆          ┆           │
│ 115  ┆ Grapefruit ┆ /api/v1/le ┆ GL         ┆ … ┆ null       ┆ null       ┆ null     ┆ null      │
│      ┆ League     ┆ ague/115   ┆            ┆   ┆            ┆            ┆          ┆           │
│ 117  ┆ Internatio ┆ /api/v1/le ┆ INT        ┆ … ┆ 2.7        ┆ 2.4        ┆ 11       ┆ /api/v1/s │
│      ┆ nal League ┆ ague/117   ┆            ┆   ┆            ┆            ┆          ┆ ports/11  │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …        ┆ …         │
│ 108  ┆ NOT USED - ┆ /api/v1/le ┆ N/A        ┆ … ┆ null       ┆ null       ┆ 22       ┆ /api/v1/s │
│      ┆ DELETE OR  ┆ ague/108   ┆            ┆   ┆            ┆            ┆          ┆ ports/22  │
│      ┆ DEPRECATE  ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ 587  ┆ Showcase   ┆ /api/v1/le ┆ SG         ┆ … ┆ null       ┆ null       ┆ 586      ┆ /api/v1/s │
│      ┆ Games      ┆ ague/587   ┆            ┆   ┆            ┆            ┆          ┆ ports/586 │
│ 625  ┆ Tournament ┆ /api/v1/le ┆ T12        ┆ … ┆ null       ┆ null       ┆ null     ┆ null      │
│      ┆ 12         ┆ ague/625   ┆            ┆   ┆            ┆            ┆          ┆           │
│ 577  ┆ National   ┆ /api/v1/le ┆ NPF        ┆ … ┆ null       ┆ null       ┆ 576      ┆ /api/v1/s │
│      ┆ Pro        ┆ ague/577   ┆            ┆   ┆            ┆            ┆          ┆ ports/576 │
│      ┆ Fastpitch  ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ 6044 ┆ Athletes   ┆ /api/v1/le ┆ AUSL       ┆ … ┆ null       ┆ null       ┆ 576      ┆ /api/v1/s │
│      ┆ Unlimited  ┆ ague/6044  ┆            ┆   ┆            ┆            ┆          ┆ ports/576 │
│      ┆ Softball   ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ Le…        ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴───────────┘

In [5]:
CREATE_leagues = '''
    CREATE TABLE leagues(
        league_id INT PRIMARY KEY,
        sport_id INT REFERENCES sports(sport_id),
        league_name VARCHAR(255) NOT NULL,
        league_abbr VARCHAR(255) NOT NULL,
        is_active BOOLEAN NOT NULL,
        sort_order INT NOT NULL CHECK (sort_order > 0),
        league_link VARCHAR(255) UNIQUE NOT NULL
        ------------------------------------------------
        CONSTRAINT league_link_format CHECK (league_link ~ link_regex)
    )
'''
CREATE_leagues = CREATE_leagues.replace('link_regex', '\'' + link_regex + '\'')
print(CREATE_leagues)

    CREATE TABLE leagues(
        league_id INT PRIMARY KEY,
        sport_id INT REFERENCES sports(sport_id),
        league_name VARCHAR(255) NOT NULL,
        league_abbr VARCHAR(255) NOT NULL,
        is_active BOOLEAN NOT NULL,
        sort_order INT NOT NULL CHECK (sort_order > 0),
        league_link VARCHAR(255) UNIQUE NOT NULL
        ------------------------------------------------
        CONSTRAINT league_link_format CHECK (league_link ~ '/api/v\d(?:\.\d)?((?:/[a-zA-Z0-9]+)+)')
    )

In [6]:
get_divisions()

shape: (61, 14)
┌──────┬─────────────┬────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ id   ┆ name        ┆ season ┆ nameShort   ┆ … ┆ league.link ┆ sport.id ┆ sport.link ┆ numPlayoff │
│ ---  ┆ ---         ┆ ---    ┆ ---         ┆   ┆ ---         ┆ ---      ┆ ---        ┆ Teams      │
│ i64  ┆ str         ┆ str    ┆ str         ┆   ┆ str         ┆ i64      ┆ str        ┆ ---        │
│      ┆             ┆        ┆             ┆   ┆             ┆          ┆            ┆ i64        │
╞══════╪═════════════╪════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 6007 ┆ North       ┆ 2026   ┆ North       ┆ … ┆ /api/v1/lea ┆ 6005     ┆ /api/v1/sp ┆ null       │
│      ┆ Region      ┆        ┆             ┆   ┆ gue/6006    ┆          ┆ orts/6005  ┆            │
│ 6011 ┆ Cape Cod    ┆ 2026   ┆ CCBL East   ┆ … ┆ /api/v1/lea ┆ 22       ┆ /api/v1/sp ┆ 4          │
│      ┆ East        ┆        ┆             ┆   ┆ gue/565     ┆          ┆ orts/22    ┆            │
│      ┆ Division    ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
│ 236  ┆ Pioneer     ┆ 2026   ┆ PIO South   ┆ … ┆ /api/v1/lea ┆ 23       ┆ /api/v1/sp ┆ 1          │
│      ┆ League      ┆        ┆             ┆   ┆ gue/128     ┆          ┆ orts/23    ┆            │
│      ┆ South       ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
│ 205  ┆ National    ┆ 2026   ┆ NL Central  ┆ … ┆ /api/v1/lea ┆ 1        ┆ /api/v1/sp ┆ 1          │
│      ┆ League      ┆        ┆             ┆   ┆ gue/104     ┆          ┆ orts/1     ┆            │
│      ┆ Central     ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
│ 200  ┆ American    ┆ 2026   ┆ AL West     ┆ … ┆ /api/v1/lea ┆ 1        ┆ /api/v1/sp ┆ 1          │
│      ┆ League West ┆        ┆             ┆   ┆ gue/103     ┆          ┆ orts/1     ┆            │
│ …    ┆ …           ┆ …      ┆ …           ┆ … ┆ …           ┆ …        ┆ …          ┆ …          │
│ 561  ┆ Arizona     ┆ 2026   ┆ ACL West    ┆ … ┆ /api/v1/lea ┆ 16       ┆ /api/v1/sp ┆ 1          │
│      ┆ Complex     ┆        ┆             ┆   ┆ gue/121     ┆          ┆ orts/16    ┆            │
│      ┆ League West ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
│ 410  ┆ LVBP        ┆ 2020   ┆ LVBP        ┆ … ┆ /api/v1/lea ┆ 17       ┆ /api/v1/sp ┆ 2          │
│      ┆ Central     ┆        ┆ Oriental    ┆   ┆ gue/135     ┆          ┆ orts/17    ┆            │
│      ┆ Division    ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
│ 411  ┆ LVBP        ┆ 2020   ┆ LVBP        ┆ … ┆ /api/v1/lea ┆ 17       ┆ /api/v1/sp ┆ 2          │
│      ┆ Occidental  ┆        ┆ Occidental  ┆   ┆ gue/135     ┆          ┆ orts/17    ┆            │
│      ┆ Division    ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
│ 6010 ┆ Centro      ┆ 2026   ┆ Centro      ┆ … ┆ /api/v1/lea ┆ 6005     ┆ /api/v1/sp ┆ null       │
│      ┆ Region      ┆        ┆             ┆   ┆ gue/6006    ┆          ┆ orts/6005  ┆            │
│ 570  ┆ Arizona     ┆ 2026   ┆ ACL Central ┆ … ┆ /api/v1/lea ┆ 16       ┆ /api/v1/sp ┆ 1          │
│      ┆ Complex     ┆        ┆             ┆   ┆ gue/121     ┆          ┆ orts/16    ┆            │
│      ┆ League      ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
│      ┆ Central     ┆        ┆             ┆   ┆             ┆          ┆            ┆            │
└──────┴─────────────┴────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [7]:
CREATE_divisions = '''
CREATE TABLE divisions(
    division_id INT PRIMARY KEY,
    league_id INT REFERENCES leagues(league_id),
    division_name VARCHAR(255) UNIQUE NOT NULL,
    division_name_sort VARCHAR(255) UNIQUE NOT NULL,
    sort_order INT UNIQUE NOT NULL CHECK (sort_order > 0),
    division_link VARCHAR(255) UNIQUE NOT NULL,
    ----------------------------------------------
    CONSTRAINT division_link_format CHECK (division_link ~ link_regex)
)
'''
CREATE_divisions = CREATE_divisions.replace('link_regex', '\'' + link_regex + '\'')
print(CREATE_divisions)

CREATE TABLE divisions(
    division_id INT PRIMARY KEY,
    league_id INT REFERENCES leagues(league_id),
    division_name VARCHAR(255) UNIQUE NOT NULL,
    division_name_sort VARCHAR(255) UNIQUE NOT NULL,
    sort_order INT UNIQUE NOT NULL CHECK (sort_order > 0),
    division_link VARCHAR(255) UNIQUE NOT NULL,
    ----------------------------------------------
    CONSTRAINT division_link_format CHECK (division_link ~ '/api/v\d(?:\.\d)?((?:/[a-zA-Z0-9]+)+)')
)

In [25]:
with db.connect('saber.db') as con:
    con.begin()#begin transaction

    #drop current tables
    table_names = con.sql('show tables').pl()['name']
    DROP = 'DROP TABLE IF EXISTS {}'
    for table in table_names:
        con.sql(DROP.format(table))

    try:
        #creatae tables
        con.sql(CREATE_sports)
        con.sql(CREATE_leagues)
        con.sql(CREATE_divisions)
    except:
        #rollback on error
        con.rollback()
    finally:
        #commit changes
        con.commit()

    print(con.sql('show tables').pl())

shape: (3, 1)
┌───────────┐
│ name      │
│ ---       │
│ str       │
╞═══════════╡
│ divisions │
│ leagues   │
│ sports    │
└───────────┘