In [86]:

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [87]:


import polars as pl
#from polars import selectors as cs
from extract import endpoints, get, get_leagues
from transform import transform_sports, transform_leagues, transform_seasons, transform_divisions
from transform import DivisionSchema, DivisionSeasonsSchema,SportSchema, LeagueSchema, SeasonSchema
from transform import SportsSeasons
from pathlib import Path

In [88]:
data = Path('data')
tables = endpoints.keys()
paths = [data/(table+'.parquet') for table in tables]

In [89]:
for table, path in zip(tables, paths):
    if not path.exists():
        get(table).collect().write_parquet(path)

In [90]:
sports = pl.scan_parquet(data/'sports.parquet')
leagues = pl.scan_parquet(data/'leagues.parquet')
divisions = pl.scan_parquet(data/'divisions.parquet')
seasons = pl.scan_parquet(data/'seasons.parquet')
teams = pl.scan_parquet(data/'teams.parquet')

In [91]:
sports = transform_sports(sports)
sports = SportSchema.validate(sports, cast=True).lazy()

In [92]:
leagues = transform_leagues(leagues)
leagues = LeagueSchema.validate(leagues, cast=True).lazy()

In [93]:
lf = pl.scan_parquet('data/seasons.parquet')
seasons  = transform_seasons(lf)
seasons = SeasonSchema.validate(seasons, cast=True).lazy()

In [94]:
SC, bad = SportsSeasons.filter(
    {
        'sports': sports,
        'seasons': seasons,
    }
)

In [95]:
bad['sports']._df

shape: (8, 21)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sport_id ┆ sport_cod ┆ sport_nam ┆ sport_abb ┆ … ┆ sport_lin ┆ sport_lin ┆ sport_lin ┆ seasons_s │
│ ---      ┆ e         ┆ e         ┆ r         ┆   ┆ k|nullabi ┆ k|unique  ┆ k|regex   ┆ ports     │
│ u32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ lity      ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ bool      ┆ bool      ┆ bool      │
│          ┆           ┆           ┆           ┆   ┆ bool      ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 21       ┆ min       ┆ Minor     ┆ Minors    ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ League    ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 61       ┆ nlb       ┆ Negro     ┆ NLB       ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ League    ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32       ┆ kor       ┆ Korean    ┆ KOR       ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Organizat ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31       ┆ jml       ┆ Nippon    ┆ NPB       ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ Professio ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ nal       ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 509      ┆ nae       ┆ Internati ┆ 18U       ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ onal      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ (18U)     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 510      ┆ nas       ┆ Internati ┆ 16U       ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ onal      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ (16 and…  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 6005     ┆ ame       ┆ Internati ┆ AME       ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ onal      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ (amateu…  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 52       ┆ oly       ┆ Olympic   ┆ OLY       ┆ … ┆ null      ┆ null      ┆ null      ┆ false     │
│          ┆           ┆ Baseball  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [99]:
SC.sports.collect()

shape: (14, 6)
┌──────────┬────────────┬───────────────────────┬────────────┬────────────┬─────────────────────┐
│ sport_id ┆ sport_code ┆ sport_name            ┆ sport_abbr ┆ sort_order ┆ sport_link          │
│ ---      ┆ ---        ┆ ---                   ┆ ---        ┆ ---        ┆ ---                 │
│ u32      ┆ str        ┆ str                   ┆ str        ┆ u32        ┆ str                 │
╞══════════╪════════════╪═══════════════════════╪════════════╪════════════╪═════════════════════╡
│ 1        ┆ mlb        ┆ Major League Baseball ┆ MLB        ┆ 11         ┆ /api/v1/sports/1    │
│ 11       ┆ aaa        ┆ Triple-A              ┆ AAA        ┆ 101        ┆ /api/v1/sports/11   │
│ 12       ┆ aax        ┆ Double-A              ┆ AA         ┆ 201        ┆ /api/v1/sports/12   │
│ 13       ┆ afa        ┆ High-A                ┆ A+         ┆ 301        ┆ /api/v1/sports/13   │
│ 14       ┆ afx        ┆ Single-A              ┆ A          ┆ 401        ┆ /api/v1/sports/14   │
│ …        ┆ …          ┆ …                     ┆ …          ┆ …          ┆ …                   │
│ 22       ┆ bbc        ┆ College Baseball      ┆ College    ┆ 5101       ┆ /api/v1/sports/22   │
│ 586      ┆ hsb        ┆ High School Baseball  ┆ H.S.       ┆ 6201       ┆ /api/v1/sports/586  │
│ 576      ┆ wps        ┆ Women's Professional  ┆ WPS        ┆ 7001       ┆ /api/v1/sports/576  │
│          ┆            ┆ Softball              ┆            ┆            ┆                     │
│ 15       ┆ asx        ┆ Class A Short Season  ┆ A(Short)   ┆ 501        ┆ /api/v1/sports/15   │
│ 5442     ┆ roa        ┆ Rookie Advanced       ┆ ROA        ┆ 601        ┆ /api/v1/sports/5442 │
└──────────┴────────────┴───────────────────────┴────────────┴────────────┴─────────────────────┘

In [97]:
div, div_seasons = transform_divisions(divisions, leagues)

In [98]:
divisions = DivisionSchema.validate(div, cast=True).lazy()
division_seasons = DivisionSeasonsSchema.validate(div_seasons, cast=True).lazy()